name: Deploy Staging Environment

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: select terraform action
        options:
        - apply
        - destroy
        required: true

  push:
    branches:
      - stg

permissions:
  contents: read
  id-token: write

jobs:
  deploy_site:
    name: Deploy Staging Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: env/stg

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.STG_IAM_ROLE }}
          role-session-name: github-actions

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform apply
        if: ${{ github.event.inputs.terraform_action == 'apply' }}
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.3
          tf_actions_subcommand: ${{ github.event.inputs.terraform_action }}
          tf_actions_working_dir: './env/stg'
          tf_actions_comment: true
          args: '--auto-approve'
      
      - name: Terraform destroy
        if: ${{ github.event.inputs.terraform_action == 'destroy' }}
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.3
          tf_actions_subcommand: ${{ github.event.inputs.terraform_action }}
          tf_actions_working_dir: './env/stg'
          tf_actions_comment: true
          args: '--auto-approve'